# Generated by Django 3.1.3 on 2020-11-20 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0002_auto_20201119_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='id',
            new_name='idMatricula',
        ),
    ]
